name: multiple jobs

on: push

jobs: 
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: clone the repo
          uses: actions/checkout@v4
          run : sleep 30s
    test_job: 
        runs-on: ubuntu-latest
        steps:
        - name: lsit files
          run: ls- ltra
    deploy_job:
        runs-on: ubuntu-latest
        steps: 
        - name: read the file
          run: cat README.md
          